
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saketh
 */
public class RegisterNewWorker extends javax.swing.JFrame {

    /**
     * Creates new form RegisterNewWorker
     */
    public RegisterNewWorker() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        missingAlert = new javax.swing.JFrame();
        alertMessage = new javax.swing.JLabel();
        mismatchAlert = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        repeatAlert = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        successAlert = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        intAlert = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputContactNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        inputLoginId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        inputConfirmPassword = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        missingAlert.setTitle("Missing Information");
        missingAlert.setSize(new java.awt.Dimension(300, 100));

        alertMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert-icon-red-outline (1).png"))); // NOI18N
        alertMessage.setText("Please Enter all the details.");

        javax.swing.GroupLayout missingAlertLayout = new javax.swing.GroupLayout(missingAlert.getContentPane());
        missingAlert.getContentPane().setLayout(missingAlertLayout);
        missingAlertLayout.setHorizontalGroup(
            missingAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(missingAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alertMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        missingAlertLayout.setVerticalGroup(
            missingAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(missingAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alertMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        mismatchAlert.setTitle("Passwords Mismatch");
        mismatchAlert.setSize(new java.awt.Dimension(300, 100));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert-icon-red-outline (1).png"))); // NOI18N
        jLabel9.setText("Entered passwords do not match!");

        javax.swing.GroupLayout mismatchAlertLayout = new javax.swing.GroupLayout(mismatchAlert.getContentPane());
        mismatchAlert.getContentPane().setLayout(mismatchAlertLayout);
        mismatchAlertLayout.setHorizontalGroup(
            mismatchAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mismatchAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        mismatchAlertLayout.setVerticalGroup(
            mismatchAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mismatchAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        repeatAlert.setTitle("Error!");
        repeatAlert.setSize(new java.awt.Dimension(400, 100));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert-icon-red-outline (1).png"))); // NOI18N
        jLabel10.setText("Username already exists. Please choose another.");

        javax.swing.GroupLayout repeatAlertLayout = new javax.swing.GroupLayout(repeatAlert.getContentPane());
        repeatAlert.getContentPane().setLayout(repeatAlertLayout);
        repeatAlertLayout.setHorizontalGroup(
            repeatAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repeatAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        repeatAlertLayout.setVerticalGroup(
            repeatAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repeatAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );

        successAlert.setTitle("Success");
        successAlert.setSize(new java.awt.Dimension(300, 100));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/success (1).png"))); // NOI18N
        jLabel11.setText("Successfully registered new worker!");

        javax.swing.GroupLayout successAlertLayout = new javax.swing.GroupLayout(successAlert.getContentPane());
        successAlert.getContentPane().setLayout(successAlertLayout);
        successAlertLayout.setHorizontalGroup(
            successAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        successAlertLayout.setVerticalGroup(
            successAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        intAlert.setPreferredSize(new java.awt.Dimension(400, 100));
        intAlert.setSize(new java.awt.Dimension(400, 100));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert-icon-red-outline (1).png"))); // NOI18N
        jLabel12.setText("Enter integer phone number only!");

        javax.swing.GroupLayout intAlertLayout = new javax.swing.GroupLayout(intAlert.getContentPane());
        intAlert.getContentPane().setLayout(intAlertLayout);
        intAlertLayout.setHorizontalGroup(
            intAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        intAlertLayout.setVerticalGroup(
            intAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register New Worker");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please enter your details");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        inputName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("Contact Number");

        inputContactNumber.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Location of work");

        inputLocation.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setText("Type of Work");

        inputType.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        inputType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "Electrical", "Plumbing", "Sweeping", "Civil/Maintainence" }));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setText("Login Id");

        inputLoginId.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setText("Password");

        inputPassword.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setText("Re-enter Password");

        inputConfirmPassword.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        submitButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submit.jpeg"))); // NOI18N
        submitButton.setText("Submit");
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset (1).jpeg"))); // NOI18N
        resetButton.setText("Reset");
        resetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        goBackButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        goBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back (1).png"))); // NOI18N
        goBackButton.setText("Go Back");
        goBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(submitButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputLoginId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputConfirmPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(5, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {resetButton, submitButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(resetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goBackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        WorkerLogin workerLogin = new WorkerLogin();
        this.setVisible(false);
        workerLogin.setVisible(true);
        
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        RegisterNewWorker registerNewWorker = new RegisterNewWorker();
        this.setVisible(false);
        registerNewWorker.setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int state = validDetails(inputName.getText(), inputContactNumber.getText(), inputLocation.getText(), inputLoginId.getText(),inputType.getSelectedIndex(), String.valueOf(inputPassword.getPassword()), String.valueOf(inputConfirmPassword.getPassword()));
        if( state == 1){
                this.missingAlert.setVisible(true);
        }
        else if(state == 2){
            this.mismatchAlert.setVisible(true);
        }
        else if(state == 3){
            this.repeatAlert.setVisible(true);
        }
        else{
            if(state == 0){
                int x = Integer.parseInt(inputContactNumber.getText());
                String name = inputName.getText();
                String contactNumber = inputContactNumber.getText();
                String location = inputLocation.getText();
                String type = inputType.getSelectedItem().toString();
                String loginId = inputLoginId.getText();
                String password = String.valueOf(inputPassword.getPassword());
                Worker worker = new Worker(name,contactNumber,location,type,loginId,password);
                worker.workerId = WorkerDatabase.registerNewWorker(worker);
                this.successAlert.setVisible(true);
                ComplaintDatabase.assignAll(worker);
            }
            else if(state == 4){
                this.intAlert.setVisible(true);
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    public int validDetails(String inputName, String inputContactNumber, String inputLocation, String inputLoginId, int typeSelected,String inputLoginPassword,  String inputConfirmPassword)
    {
        if(inputName.equals("") || inputContactNumber.equals("") || inputLocation.equals("") || 
           inputLoginId.equals("") || typeSelected == 0 || inputPassword.equals("")|| inputLoginPassword.equals("")|| inputConfirmPassword.equals("")){
                return 1;
        }
        else if(!inputLoginPassword.equals(inputConfirmPassword)){
            return 2;
        }
        else if(WorkerDatabase.getWorkerData(inputLoginId) != null){
            return 3;
        }
        else{
            try{
                int x = Integer.parseInt(inputContactNumber);
                return 0;
            }
            catch(NumberFormatException nfx){
                return 4;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertMessage;
    private javax.swing.JButton goBackButton;
    private javax.swing.JPasswordField inputConfirmPassword;
    private javax.swing.JTextField inputContactNumber;
    private javax.swing.JTextField inputLocation;
    private javax.swing.JTextField inputLoginId;
    private javax.swing.JTextField inputName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JComboBox<String> inputType;
    private javax.swing.JFrame intAlert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFrame mismatchAlert;
    private javax.swing.JFrame missingAlert;
    private javax.swing.JFrame repeatAlert;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JFrame successAlert;
    // End of variables declaration//GEN-END:variables
}
