
import java.util.ArrayList;
import javax.swing.JFrame;

public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     * @param user
     */
    private User user = null;
    public UserInterface(User user) {
        initComponents();
        this.welcomeLabel.setText(this.welcomeLabel.getText()+ user.name);
        this.user = user;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        contactNumber = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactDetails = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        alert = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deleteAlert = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        deleteErrorAlert = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        phoneAlert = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        editError = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        newComplaintButton = new javax.swing.JButton();
        viewComplaintButton = new javax.swing.JButton();
        viewProfileButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        profileFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        profileFrame.setTitle("User Profile");
        profileFrame.setSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Profile");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Name: ");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Contact Number");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setText("Contact Details");

        name.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        contactNumber.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        editButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit(1).png"))); // NOI18N
        editButton.setText("Edit");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        goBackButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        goBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back (1).png"))); // NOI18N
        goBackButton.setText("Go Back");
        goBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        contactDetails.setColumns(20);
        contactDetails.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        contactDetails.setRows(5);
        jScrollPane1.setViewportView(contactDetails);

        saveButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save (1).png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete (1).png"))); // NOI18N
        deleteButton.setText("Delete ");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profileFrameLayout = new javax.swing.GroupLayout(profileFrame.getContentPane());
        profileFrame.getContentPane().setLayout(profileFrameLayout);
        profileFrameLayout.setHorizontalGroup(
            profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileFrameLayout.createSequentialGroup()
                .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(profileFrameLayout.createSequentialGroup()
                        .addContainerGap(121, Short.MAX_VALUE)
                        .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileFrameLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileFrameLayout.createSequentialGroup()
                                .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name)
                            .addComponent(contactNumber)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(profileFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(goBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profileFrameLayout.setVerticalGroup(
            profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileFrameLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addGap(34, 34, 34)
                .addComponent(goBackButton)
                .addContainerGap())
        );

        alert.setTitle("Error!");
        alert.setSize(new java.awt.Dimension(400, 100));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert-icon-red-outline (1).png"))); // NOI18N
        jLabel3.setText("Sorry. The complaint database if full right now.");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Please try again later.");

        javax.swing.GroupLayout alertLayout = new javax.swing.GroupLayout(alert.getContentPane());
        alert.getContentPane().setLayout(alertLayout);
        alertLayout.setHorizontalGroup(
            alertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        alertLayout.setVerticalGroup(
            alertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteAlert.setTitle("Success");
        deleteAlert.setSize(new java.awt.Dimension(300, 100));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/success (1).png"))); // NOI18N
        jLabel7.setText("Successfully deleted user");

        javax.swing.GroupLayout deleteAlertLayout = new javax.swing.GroupLayout(deleteAlert.getContentPane());
        deleteAlert.getContentPane().setLayout(deleteAlertLayout);
        deleteAlertLayout.setHorizontalGroup(
            deleteAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        deleteAlertLayout.setVerticalGroup(
            deleteAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        deleteErrorAlert.setTitle("Error!");
        deleteErrorAlert.setSize(new java.awt.Dimension(300, 100));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert-icon-red-outline (1).png"))); // NOI18N
        jLabel8.setText("Error in deleting user");

        javax.swing.GroupLayout deleteErrorAlertLayout = new javax.swing.GroupLayout(deleteErrorAlert.getContentPane());
        deleteErrorAlert.getContentPane().setLayout(deleteErrorAlertLayout);
        deleteErrorAlertLayout.setHorizontalGroup(
            deleteErrorAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteErrorAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        deleteErrorAlertLayout.setVerticalGroup(
            deleteErrorAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteErrorAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        phoneAlert.setSize(new java.awt.Dimension(400, 100));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert-icon-red-outline (1).png"))); // NOI18N
        jLabel9.setText("Enter only integer phone number!");

        javax.swing.GroupLayout phoneAlertLayout = new javax.swing.GroupLayout(phoneAlert.getContentPane());
        phoneAlert.getContentPane().setLayout(phoneAlertLayout);
        phoneAlertLayout.setHorizontalGroup(
            phoneAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        phoneAlertLayout.setVerticalGroup(
            phoneAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        editError.setPreferredSize(new java.awt.Dimension(300, 100));
        editError.setSize(new java.awt.Dimension(300, 100));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert-icon-red-outline (1).png"))); // NOI18N
        jLabel10.setText("Please enter all details!");

        javax.swing.GroupLayout editErrorLayout = new javax.swing.GroupLayout(editError.getContentPane());
        editError.getContentPane().setLayout(editErrorLayout);
        editErrorLayout.setHorizontalGroup(
            editErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        editErrorLayout.setVerticalGroup(
            editErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Interface");

        welcomeLabel.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome! ");

        newComplaintButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        newComplaintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/complaint_form (1) (1).png"))); // NOI18N
        newComplaintButton.setText("   File New Complaint");
        newComplaintButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newComplaintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newComplaintButtonActionPerformed(evt);
            }
        });

        viewComplaintButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        viewComplaintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view (1) (1) (1).png"))); // NOI18N
        viewComplaintButton.setText("View your complaints");
        viewComplaintButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewComplaintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewComplaintButtonActionPerformed(evt);
            }
        });

        viewProfileButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        viewProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile (1) (1).png"))); // NOI18N
        viewProfileButton.setText("View your profile");
        viewProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (1).jpeg"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 122, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newComplaintButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewComplaintButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(newComplaintButton)
                .addGap(18, 18, 18)
                .addComponent(viewComplaintButton)
                .addGap(18, 18, 18)
                .addComponent(viewProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        UserLogin userLogin = new UserLogin();
        this.setVisible(false);
        userLogin.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void viewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButtonActionPerformed
        // TODO add your handling code here:
        this.name.setText(user.name);
        this.contactNumber.setText(user.getContactNumber());
        this.contactDetails.setText(user.getContactDetails());
        this.name.setEditable(false);
        this.contactNumber.setEditable(false);
        this.contactDetails.setEditable(false);
        this.saveButton.setEnabled(false);
        this.profileFrame.setVisible(true);
        
    }//GEN-LAST:event_viewProfileButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        this.profileFrame.setVisible(false);
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        this.name.setEditable(true);
        this.contactNumber.setEditable(true);
        this.contactDetails.setEditable(true);
        this.saveButton.setEnabled(true);
        this.editButton.setEnabled(false);
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        int state = validDetails(this.name.getText() , this.contactNumber.getText(), this.contactDetails.getText());
        if(state == 0){
            User modifyUser = new User(this.name.getText(),this.contactNumber.getText(),this.contactDetails.getText(),user.getLoginId(),user.getLoginPswrd());
            UserDatabase.modifyUserData(modifyUser);
            this.saveButton.setEnabled(false);
            this.editButton.setEnabled(true);
            this.name.setEditable(false);
            this.contactNumber.setEditable(false);
            this.contactDetails.setEditable(false);
            user = UserDatabase.getUserData(user.getLoginId());
            this.name.setText(user.name);
            this.contactNumber.setText(user.getContactNumber());
            this.contactDetails.setText(user.getContactDetails());
            this.welcomeLabel.setText("Welcome! " + user.name);
        }
        else if(state == 2){
            this.phoneAlert.setVisible(true);
        }
        else if(state == 1){
            this.editError.setVisible(true);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    public int validDetails(String name, String contactNumber, String contactDetails)
    {
        if(name.equals("") || contactDetails.equals("") || contactNumber.equals(""))
            return 1;
        else{
            try{
                int x = Integer.parseInt(contactNumber);
                return 0;
            }
            catch(NumberFormatException nfx){
                return 2;
            }
        }
    }
    private void newComplaintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newComplaintButtonActionPerformed
        // TODO add your handling code here:
        if(ComplaintDatabase.getSize()< ComplaintDatabase.getMaxComplaints()){
            ComplaintForm complaintForm = new ComplaintForm(user);
            this.setVisible(false);
            complaintForm.setVisible(true);
        }
        else{
            this.alert.setVisible(true);
        }
    }//GEN-LAST:event_newComplaintButtonActionPerformed

    private void viewComplaintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewComplaintButtonActionPerformed
        // TODO add your handling code here:
        ViewComplaints viewComplaint = new ViewComplaints(user);
        this.setVisible(false);
        viewComplaint.setVisible(true);
    }//GEN-LAST:event_viewComplaintButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        ArrayList<Complaint> complaintData = ComplaintDatabase.getComplaintDataByUserId(user.getLoginId());
        if(!complaintData.isEmpty()){
            for(int i=0;i<complaintData.size();i++){
                ComplaintDatabase.deleteComplaint(complaintData.get(i));
            }
        }
        boolean deleted = UserDatabase.deleteUser(user);
        if(deleted){
        UserLogin userLogin = new UserLogin();
        this.setVisible(false);
        this.profileFrame.setVisible(false);
        userLogin.setVisible(true);
        this.deleteAlert.setVisible(true);
        }
        else{
            this.deleteErrorAlert.setVisible(true);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame alert;
    private javax.swing.JTextArea contactDetails;
    private javax.swing.JTextField contactNumber;
    private javax.swing.JFrame deleteAlert;
    private javax.swing.JButton deleteButton;
    private javax.swing.JFrame deleteErrorAlert;
    private javax.swing.JButton editButton;
    private javax.swing.JFrame editError;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField name;
    private javax.swing.JButton newComplaintButton;
    private javax.swing.JFrame phoneAlert;
    private javax.swing.JFrame profileFrame;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton viewComplaintButton;
    private javax.swing.JButton viewProfileButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
